### ISSUE TITLE
Pictures with Location Pins Android

### ISSUE THREAD

**Issue by bmwalker2005** [Team2Beyond/Street-Art-Atlanta#10]
Associate the pictures with the location pins and display them when pins are clicked on Android.

"As a user, I want to see a picture of the street art so I know what to expect."

@EmekeN Work on implementing the android UI portion
@bryson Work on implementing the picture database table and uploading pictures to it
@ttran90 Work on pulling pictures from the database and loading them in the appropriate ui elements

**Comment by EmekeN** [comment]
I added code for making pictures from byte streams and for making pictures with url. Need to test with DB elements
